### ISSUE TITLE
No sound at all in beta OSX app

### ISSUE THREAD

**Issue by shawncreed** [pdaddyo/soundbounce#144] opened 2015-01-04 03:44 UTC
Hi there! The app looks great... I was so excited to find it especially after Soundrop going away. But the OSX app doesn't play any sound for me. It shows the player progress bar moving so it looks like it's playing, but no sound. Other apps are playing sound just fine. Any ideas? Let me know what other info I might be able to provide to help you diagnose the problem.

-Shawn

**Comment by pdaddyo** [comment] 2015-01-04 09:00
Duplicate of issue #90 - my reply there:

"Have you guys tried again since?  This is a known issue on first launch
with libspotify, especially on OSX.  Let us know how you get on when you
restart, leave for 5 minutes, close and restart again.  This usually sorts
it out."

**Closed** 2015-01-04 10:54 UTC
Labels: duplicate
