### ISSUE TITLE
Suggested Feature - History via RSS or simply channel play history (maybe the last 5, 10, or 25 songs?)

### ISSUE THREAD

**Issue by inzi** [pdaddyo/soundbounce#175] opened 2015-01-09 20:44 UTC
Heard a song someone added and it was great - but I was tied up and couldn't get to my computer to star it. Once it finished, there's no way to find out what played.

In SoundDrop - the last song played would automatically drop to the bottom of the queue. 

With SoundBounce, there is no such way to find it.

**Comment by pdaddyo** [comment] 2015-01-09 23:27
Good idea, dupe of #147

**Closed by pdaddyo** 2015-01-09 23:27 UTC
Labels: wontfix
