### ISSUE TITLE
Once a song is playing it should not get bumped by another song, unless it is deleted by an admin.

### ISSUE THREAD

**Issue by bgod** [pdaddyo/soundbounce#135] opened 2014-12-31 20:52 UTC
Someone just reported: "That's weird. Seems that if a song suddenly has more votes than the one playing, it starts playing immediately, and the other song moves back into the queue"

**Comment by pdaddyo** [comment] 2015-01-01 17:44
Once a song is playing, it can't be voted on or bumped off by another track with more votes, so not sure what the user experienced here.  I wonder if an admin removed the track?  Closing unless it's seen by other users.

**Closed by pdaddyo** 2015-01-01 17:44 UTC

**Comment by bgod** [comment] 2015-01-01 18:53
I don't think an admin deleted it.  As far as I know, I'm the only admin for the room.  And supposedly the timing was that it happened as soon as the track got more votes than the playing track.  Is there a preference for recently added tracks over top up tracks?  In any case, we'll re-open if it happens again.  Thanks.

**Comment by pdaddyo** [comment] 2015-01-02 11:36
Top up tracks have zero votes, so any vote / add will go above them,
however the playing track can in theory *never* be bumped without an admin
deleting.  Hopefully it was a network glitch whereby they were playing
catch-up to votes / adds that had happened, and the client corrected
itself.  Not normal / intended behaviour when internet connection is
reliable though!
